HAI
HOW DUZ I FIBONACCI YR N
    BOTH SAEM N AN 0
    O RLY?
	YA RLY
	    FOUND YR 0
    OIC
    BOTH SAEM N AN 1
    O RLY?
	YA RLY
	    FOUND YR 1
    OIC
    I HAS A F2 ITZ 0
    I HAS A F1 ITZ 1
    I HAS A INDEX ITZ 2
    I HAS A M
    IM IN YR LOOP
	M R SUM OF F1 AN F2
	F2 R F1
	F1 R M
	BOTH SAEM INDEX AN N
	O RLY?
	    YA RLY
		GTFO
	    NO WAY
		INDEX R SUM OF INDEX AN 1
	OIC
    IM OUTTA YR LOOP
    FOUND YR F1
IF U SAY SO
I HAS A PARAM
VISIBLE "Podaj parametr::"
GIMMEH PARAM
PARAM IS NOW A NUMBR
VISIBLE SMOOSH "Rozwiazanie:: " AN FIBONACCI PARAM MKAY
KTHXBYE